config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users, controllers: {registrations: :registrations, sessions: :sessions}
  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: {registrations: :registrations, sessions: :sessions}      
      resources :users, path: '/users' do
        resources :posts, path: '/posts' do
          resources :comments, only: [:new, :create, :destroy, :index]
          resources :likes, only: [:new, :create]
        end
      end
    end
  end
  root 'users#index'
  resources :users, path: '/users' do
    resources :posts, path: '/posts' do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  require 'securerandom'

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :trackable
  enum role: %i[user admin]
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :user
  end
  validates :Name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :PostsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  after_save :add_token

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def add_token
    update_column(:token, JsonWebToken::EncoderJWT.jwt_encode(email))
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def index
    @users = User.all
    render json: @users
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.recent_posts
  end
end

app/views/users/_post.html.erb
<section>
    <a href=<%=user_post_path(@user.id, post.id) %>><h3>Post #<%=post.id %> </h3></a>
    <p><%=post.Text%></p>
    <div>
        <p>Comments: <%=post.comments.count %></p>
        <p>Likes: <%=post.likes.count %></p>
    </div>
</section>

app/views/users/_user.html.erb
<p> You are a [<%= user.role %>]</p>

<%if current_page?(user_path(user.id))%>
  <section>
      <% unless user.Photo.nil? %>
        <%= image_tag (user.Photo), height: '115', width: '115' %>
      <% end %>
      <div>
        <h2> <%= user.Name %></h2>
        <span>Number of posts: <%=user.posts.count %> </span>
      </div>
    </section>
<%else%>
  <a href=<%= user_path(user.id) %>>
    <section>
      <% unless user.Photo.nil? %>
        <%= image_tag (user.Photo), height: '115', width: '115' %>
      <% end %>
      <div>
        <h2> <%= user.Name %></h2>
        <span>Number of posts: <%=user.posts.count %> </span>
      </div>
    </section>
  </a>
<% end %>

app/views/users/index.html.erb
<%= render partial: 'user', collection: @users %>

app/views/users/show.html.erb
<%= render 'user', user: @user %>

<section>
    <h2>Bio</h2>
    <p><%=@user.Bio%></p>
</section>

<%= render partial: 'post', collection: @posts %>

<button> <%= link_to ("See all posts"), user_posts_path(@user.id) %>