config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users, controllers: {registrations: :registrations, sessions: :sessions}
  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: {registrations: :registrations, sessions: :sessions}      
      resources :users, path: '/users' do
        resources :posts, path: '/posts' do
          resources :comments, only: [:new, :create, :destroy, :index]
          resources :likes, only: [:new, :create]
        end
      end
    end
  end
  root 'users#index'
  resources :users, path: '/users' do
    resources :posts, path: '/posts' do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :Title, presence: true, length: { maximum: 250 }
  validates :Text, presence: true
  validates :CommentsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :LikesCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  def update_post_counter
    user.increment!(:PostsCounter)
  end

  def recent_comment
    comments.order(created_at: :desc).limit(5)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  include JsonWebToken
  skip_before_action :authenticate_request

  def index
    user_id = params[:user_id]
    unless user_id
      render json: { error: 'Invalid parameters' }, status: 400
      return
    end
    token = User.find(user_id).token
    credential = JsonWebToken::EncoderJWT.jwt_decode(token)
    if authenticate_request(credential)
      posts = Post.where(user_id:)
      render json: posts, status: :ok
    else
      render json: { error: 'unauthorized' }, status: 401
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path, notice: 'Your post has been created successfully'
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path, notice: 'Your post has been deleted successfully'
  end

  private

  def post_params
    defaults = { user_id: current_user.id }
    params.require(:post).permit(:Title, :Text, :user_id).reverse_merge(defaults)
  end
end

app/views/posts/_form.html.erb
<%= form_with model: @post, url: user_posts_path do |form|%>
    <% @post.errors.full_messages.each do |error|%>
        <%= error %> <br>
    <%end%>
    <%= form.label :Title%>
    <%= form.text_field :Title%>

    <br>

    <%= form.label :Text%>
    <%= form.text_area :Text%>
    
    <br>
    <%= form.submit%>
<% end %>

app/views/posts/_post.html.erb
<section>
    <div>
        <a href=<%=user_post_path(@user.id, post.id) %>><h3>Post #<%=post.id %> </h3></a>
        <p><%=post.Text%></p>
        <div>
            <p>Comments: <%=post.comments.count %></p>
            <p>Likes: <%=post.likes.count %></p>
        </div>
    </div>
    <div>
        <% post.recent_comment.each do |comment|%>
            <p><%= comment.user.Name %>: <%= comment.Text %> </p>
        <% end %>
    </div>
</section>

app/views/posts/_user.html.erb
<section>
    <% unless user.Photo.nil? %>
       <%= image_tag (user.Photo), height: '115', width: '115' %>
    <% end %>
    <div>
      <h2> <%= user.Name %></h2>
      <span>Number of posts: <%=user.posts.count %> </span>
    </div>
</section>

app/views/posts/index.html.erb
<button>
    <%= link_to 'Add new post', new_user_post_path %>
</button>

<%= render 'user', user: @user %>
<%= render partial: 'post', collection: @posts %>

app/views/posts/new.html.erb
<h1> New post </h1>
<%= render 'form'%>

app/views/posts/show.html.erb
<section>
    <h3>Post #<%= @post.id %> by <%= @user.Name %></h3>
    <div>
        <p>Comments: <%=@post.comments.count %></p>
        <p>Likes: <%=@post.likes.count %></p>
    </div>
    <p><%= @post.Text %></p>
</section>
<section>    
    <% @post.comments.order(created_at: :desc).each do |comment| %>
        <p> <%= comment.user.Name %>: <%= comment.Text %></p>
        <% if can? :destroy, comment %><%= button_to "DELETE COMMENT", user_post_comment_path(user_id:@user.id, post_id:@post.id, id: comment.id), :method=>:delete %><%end%>
    <% end %>

    <%= form_with model: Comment.new, url: user_post_comments_path(@user.id, @post.id) do |form| %>
        <% Comment.new.errors.full_messages.each do |error|%>
            <%= error %> <br>
        <%end%>
        <p>Add a new comment</p>
        <%= form.text_field :Text %>
        <%= form.submit %>
    <% end %>

    <%= form_with model: Like.new, url: user_post_likes_path(user_id: @user.id, post_id: @post.id) do |form| %>
        <%= form.submit "<3" %>
    <% end %>
</section>
<section>
  <% if can? :destroy, @post %><%= button_to "DELETE POST", user_post_path(user_id:@user.id, post_id:@post.id), :method=>:delete %><%end%>
</section>